# based on https://github.com/vegasbrianc/prometheus

version: '3'

services:

  postgres:
    image: postgres:10.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jbtc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: