spring.datasource.url: jdbc:postgresql://localhost:5440/stc_trans_customer
spring.datasource.username: postgres
spring.datasource.password: postgres
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect